Traceback (most recent call last):
  File "/home/runner/workspace/.pythonlibs/bin/evennia", line 11, in <module>
    main()
  File "/home/runner/workspace/.pythonlibs/lib/python3.11/site-packages/evennia/server/evennia_launcher.py", line 2408, in main
    init_game_directory(CURRENT_DIR, check_db=check_db, need_gamedir=need_gamedir)
  File "/home/runner/workspace/.pythonlibs/lib/python3.11/site-packages/evennia/server/evennia_launcher.py", line 1812, in init_game_directory
    django.setup()
  File "/home/runner/workspace/.pythonlibs/lib/python3.11/site-packages/django/__init__.py", line 24, in setup
    apps.populate(settings.INSTALLED_APPS)
  File "/home/runner/workspace/.pythonlibs/lib/python3.11/site-packages/django/apps/registry.py", line 124, in populate
    app_config.ready()
  File "/home/runner/workspace/.pythonlibs/lib/python3.11/site-packages/django/contrib/admin/apps.py", line 27, in ready
    self.module.autodiscover()
  File "/home/runner/workspace/.pythonlibs/lib/python3.11/site-packages/django/contrib/admin/__init__.py", line 50, in autodiscover
    autodiscover_modules("admin", register_to=site)
  File "/home/runner/workspace/.pythonlibs/lib/python3.11/site-packages/django/utils/module_loading.py", line 58, in autodiscover_modules
    import_module("%s.%s" % (app_config.name, module_to_search))
  File "/nix/store/clx0mcir7qw8zk36zbr4jra789g3knf6-python3-3.11.10/lib/python3.11/importlib/__init__.py", line 126, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "<frozen importlib._bootstrap>", line 1204, in _gcd_import
  File "<frozen importlib._bootstrap>", line 1176, in _find_and_load
  File "<frozen importlib._bootstrap>", line 1147, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 690, in _load_unlocked
  File "<frozen importlib._bootstrap_external>", line 940, in exec_module
  File "<frozen importlib._bootstrap>", line 241, in _call_with_frames_removed
  File "/home/runner/workspace/.pythonlibs/lib/python3.11/site-packages/evennia/web/admin/__init__.py", line 9, in <module>
    from .accounts import AccountAdmin
  File "/home/runner/workspace/.pythonlibs/lib/python3.11/site-packages/evennia/web/admin/accounts.py", line 26, in <module>
    from evennia.utils import create
  File "/home/runner/workspace/.pythonlibs/lib/python3.11/site-packages/evennia/utils/create.py", line 37, in <module>
    Msg = ContentType.objects.get(app_label="comms", model="msg").model_class()
          ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/runner/workspace/.pythonlibs/lib/python3.11/site-packages/django/db/models/manager.py", line 87, in manager_method
    return getattr(self.get_queryset(), name)(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/runner/workspace/.pythonlibs/lib/python3.11/site-packages/django/db/models/query.py", line 637, in get
    raise self.model.DoesNotExist(
django.contrib.contenttypes.models.ContentType.DoesNotExist: ContentType matching query does not exist.